# Generated by Django 4.2.3 on 2023-08-01 09:24

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chathistorymodel_delete_historymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVectorDataModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=300)),
                ('page_no', models.CharField(max_length=10)),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('origntext', models.CharField(max_length=20000)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
