# Generated by Django 4.2.3 on 2023-08-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_documentvectordatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFileNameVectorData',
            fields=[
                ('document_filename', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=300, unique=True)),
                ('total_page_no', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=500)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='documentvectordatamodel',
            old_name='document_name',
            new_name='document_filename',
        ),
    ]
