# Generated by Django 4.2.3 on 2023-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_documentfilenamevectordata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfilenamevectordata',
            name='document_url',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='documentfilenamevectordata',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentfilenamevectordata',
            name='total_page_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
