# Generated by Django 4.2.3 on 2023-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_documentfilenamevectordata_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvectordatamodel',
            name='embeddingtext',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
